---
- name : post conf debian cloud tofu
  hosts: debian12-webservers
  remote_user: root
  become: true

  roles:
      - debian12
      - debian12-nginx
      - debian12-mariadb
      - debian12-nodejs
