---
- name: Validate required MariaDB variables
  ansible.builtin.assert:
    that:
      - mariadb_version is defined
      - mariadb_version | length > 0
      - mariadb_root_password is defined
      - mariadb_root_password | length > 0
      - mariadb_bind_address is defined
      - mariadb_bind_address | length > 0
    fail_msg: >
      Required MariaDB variables are missing.
      Ensure MARIADB_VERSION, MARIADB_ROOT_PASS and
      MARIADB_BIND_ADDRESS environment variables are set.

- name: Disable AppStream MariaDB module
  ansible.builtin.command: dnf -y module disable mariadb
  args:
    creates: /etc/dnf/modules.d/mariadb.module
  changed_when: false

- name: Install official MariaDB repository
  ansible.builtin.get_url:
    url: "https://r.mariadb.com/downloads/mariadb_repo_setup"
    dest: /tmp/mariadb_repo_setup
    mode: '0755'

- name: Configure MariaDB {{ mariadb_version }} repository
  ansible.builtin.command: >
    /tmp/mariadb_repo_setup
    --mariadb-server-version={{ mariadb_version }}
  args:
    creates: "/etc/yum.repos.d/mariadb.repo"

- name: Install MariaDB server packages
  ansible.builtin.dnf:
    name:
      - MariaDB-server
      - MariaDB-client
      - python3-PyMySQL
    state: present

- name: Enable and start MariaDB
  ansible.builtin.systemd:
    name: mariadb
    enabled: true
    state: started

- name: Set root password
  community.mysql.mysql_user:
    name: root
    host_all: true
    password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
  register: root_password_set
  failed_when: false

- name: Deploy root .my.cnf
  copy:
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'
    content: |
      [client]
      user=root
      password="{{ mariadb_root_password }}"
      host=localhost
      socket=/var/lib/mysql/mysql.sock

      [mysqldump]
      user=root
      password="{{ mariadb_root_password }}"
      host=localhost
      socket=/var/lib/mysql/mysql.sock
      quick
      quote-names
      max_allowed_packet=512M

- name: Remove anonymous users
  community.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"


- name: Remove test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: Configure bind address
  ansible.builtin.copy:
    dest: /etc/my.cnf.d/99-bind.cnf
    owner: root
    group: root
    mode: '0644'
    content: |
      [mysqld]
      bind-address={{ mariadb_bind_address }}
  notify: Restart MariaDB