---
- name: Create node_exporter
  ansible.builtin.group:
    name: node_exporter
    state: present

- name: Create user vmagent
  ansible.builtin.user:
    name: node_exporter
    groups: node_exporter
    shell: /bin/false
    createhome: yes 
    home: /etc/node_exporter
    state: present

- name: get last version of node_exporter
  ansible.builtin.shell:
    cmd: curl -sg "https://api.github.com/repos/prometheus/node_exporter/tags" | jq -r '.[0].name'
  register: node_exporter_version

- name: show version
  debug:
     msg: "{{ node_exporter_version.stdout_lines[0] }}"

- name: show version
  debug:
     msg: " https://github.com/prometheus/node_exporter/releases/download/{{ node_exporter_version.stdout_lines[0] }}/node_exporter-{{ node_exporter_version.stdout_lines[0][1:] }}.linux-amd64.tar.gz"

- name: get binary node_exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/{{ node_exporter_version.stdout_lines[0] }}/node_exporter-{{ node_exporter_version.stdout_lines[0][1:] }}.linux-amd64.tar.gz
    dest: /tmp/
    mode: 750
    owner: node_exporter
    group: node_exporter
    remote_src: yes


- name: Copy files to bin
  copy: 
    remote_src: True 
    src: /tmp/node_exporter-{{ node_exporter_version.stdout_lines[0][1:] }}.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: 0755

- name: Change permissions on /etc/node_exporter
  file:
    path: /etc/node_exporter/
    owner: node_exporter
    group: node_exporter
    mode: '0770'
    state: directory

- name: Copy node_exporter service
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0644'

- ansible.posix.firewalld:
    port: 9100/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Restart service with daemon reload
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: node_exporter    
