---
- name: Install required packages
  ansible.builtin.dnf:
    pkg:
    - firewalld
    - python3-firewall
- name: systemd enable
  ansible.builtin.systemd_service:
    name: firewalld
    state: started
    enabled: true    
- name: Allow ssh
  ansible.posix.firewalld:
    port: 22/tcp
    permanent: true
    state: enabled
