# Scrape config example
#
scrape_configs:
  - job_name: self_scrape
    scrape_interval: 10s
    static_configs:
      - targets: ['127.0.0.1:8428'] 
  - job_name: victoriametrics
    static_configs:
    - targets:
      - http://localhost:8428/metrics