---
- name: Download minio binary
  ansible.builtin.get_url:
    url: https://dl.min.io/client/mc/release/linux-amd64/archive/mc.RELEASE.2025-04-16T18-13-26Z
    dest: /root/mc
    mode: 0755
    checksum: sha256:https://dl.min.io/client/mc/release/linux-amd64/archive/mc.RELEASE.2025-04-16T18-13-26Z.sha256sum

- name: move binary to /usr/local/bin
  ansible.builtin.copy:
    remote_src: true
    src: /root/mc
    dest: /usr/local/bin/mc
    owner: minio-user
    group: minio-user
    mode: '0755' 
