- name:  "Debian12 : msmtp"
  ansible.builtin.apt:
    pkg:
    - msmtp
    - msmtp-mta

- name: "Debian12 : umask global "
  template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    mode: 0640
    owner: root
    group: msmtp

