---
- name : post conf cloud tofu
  hosts: rocky9
  remote_user: rocky
  become: true
  module_defaults:
    ansible.builtin.setup:
      gather_subset: min

  tasks:
  - name: wait ssh connection
    wait_for_connection:
      delay: 5
      timeout: 300

  - name: "tofu : setup root key"
    ansible.builtin.copy:
      remote_src: true
      src: /home/rocky/.ssh/authorized_keys
      dest: /root/.ssh/authorized_keys
      owner: root
      group: root
      mode: '0600'

  - name: "tofu : allow root sshkey"
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '(.*)PermitRootLogin(.*)$'
      line: 'PermitRootLogin without-password'
      owner: root

  - name: "tofu : reload ssh"
    service:
      name: sshd
      state: restarted

  - name: "Tofu : disable cloud init"
    copy:
      content: ""
      dest: /etc/cloud/cloud-init.disabled
      force: false
      group: root
      owner: root
      mode: 0750

  - name: Create swap file
    shell: |
      fallocate -l 2G /swap
      chmod 600 /swap
      mkswap /swap
      swapon /swap
      cp /etc/fstab /etc/fstab.bak
      echo '/swap none swap sw 0 0' | tee -a /etc/fstab

  - sysctl:
      name: vm.swappiness
      value: '10'
      sysctl_set: true
      state: present
      reload: true

  - name: Pause for 1 minutes to update server
    pause:
      minutes: 1

