---
- name : post conf debian cloud tofu
  hosts: rocky9
  remote_user: rocky
  become: true
  gather_facts: no

  tasks:
  - name: wait ssh connection
    wait_for_connection:
      delay: 5
      timeout: 300

  - name: "tofu : setup root key"
    ansible.builtin.copy:
      remote_src: true
      src: /home/rocky/.ssh/authorized_keys
      dest: /root/.ssh/authorized_keys
      owner: root
      group: root
      mode: '0600'

  - name: "tofu : allow root sshkey"
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '(.*)PermitRootLogin(.*)$'
      line: 'PermitRootLogin without-password'
      owner: root

  - name: "tofu : reload ssh"
    service:
      name: ssh
      state: restarted
  - name: "Tofu : disable cloud init"
    copy:
      content: ""
      dest: /etc/cloud/cloud-init.disabled
      force: false
      group: root
      owner: root
      mode: 0750
