---
- name : Get all cloudimages
  hosts: proxmox
  remote_user: root
  become: true

  roles:
      - proxmox/proxmox-cloud-template
  vars_prompt:
    - name: target_storage
      prompt: Target storage for cloud image ?
      private: false      