- name: Add {{ cli_fqdn }} nginx 
  template: 
    src: nginx-{{ cli_type }}.vhost.j2 
    dest: /etc/nginx/sites-available/{{ cli_fqdn }}.conf 
    owner: root 
    group: root 
    mode: 0660

- name: Activate vhost
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ cli_fqdn }}.conf 
    dest: /etc/nginx/sites-enabled/{{ cli_fqdn }}.conf 
    owner: root 
    group: root 
    state: link

- name: Add group nginx to 
  ansible.builtin.user:
    name: nginx
    groups: "{{ cli_user }}"
    append: true    

- name: reload nginx
  systemd:
      name: nginx
      state: restarted
      enabled: True
